TRUNCATE TABLE "microservices" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "data_sources" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "data_source_fields" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "udfs" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "udf_fields" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "mapping" RESTART IDENTITY CASCADE;
